In [1]:
import numpy as np

X = np.random.random((5,5))
STD = X.std()
M = X.mean()
W = (X - M)
Z = W/STD

np.save("X_normalized.npy", Z)

print("Normal Array: \n", X)
print("Normalized Array: \n", Z)

Normal Array: 
 [[0.80420133 0.13370808 0.55657938 0.7774658  0.41003958]
 [0.47690677 0.55231141 0.67260019 0.70324233 0.1287753 ]
 [0.64330648 0.34946134 0.64882362 0.37218986 0.49715822]
 [0.77110092 0.94652015 0.47321554 0.73260247 0.0644011 ]
 [0.98752596 0.99865513 0.88740071 0.8189847  0.70497291]]
Normalized Array: 
 [[ 0.78129545 -1.84170425 -0.18741273  0.67670486 -0.760683  ]
 [-0.49909555 -0.20410922  0.26646588  0.38633932 -1.86100148]
 [ 0.15186757 -0.99766782  0.17345085 -0.90875281 -0.41987099]
 [ 0.65180515  1.33805305 -0.51353583  0.50119751 -2.11283626]
 [ 1.49846961  1.54200745  1.10677516  0.83912864  0.39310942]]
