In [2]:
import numpy as np

X = np.random.random((5,5))
STD = X.std()
M = X.mean()
W = (X - M)
Z = W/STD

print("Normal Array: \n", X)
print("Normalized Array: \n", Z)

Normal Array: 
 [[0.97134394 0.2395621  0.65246572 0.74928949 0.31513171]
 [0.31919369 0.39500257 0.43330291 0.74809323 0.60970798]
 [0.63766971 0.46085859 0.339808   0.07846744 0.94636183]
 [0.27671399 0.10654254 0.84835254 0.03822058 0.90466887]
 [0.66584666 0.20252949 0.0197354  0.88753977 0.58461945]]
Normalized Array: 
 [[ 1.61248171 -0.87639793  0.52793784  0.85724734 -0.61937644]
 [-0.60556114 -0.34772586 -0.21746172  0.85317872  0.38251355]
 [ 0.47761482 -0.12374145 -0.53544933 -1.42430058  1.52751449]
 [-0.75003982 -1.32881374  1.19417291 -1.56118508  1.38571163]
 [ 0.57344808 -1.00235039 -1.62405546  1.32745348  0.29718438]]
